-- Personal AI: every student gets their own AI output.
--
-- 1. Flashcards become a PRIVATE deck per student (owner's decision, 24 Sep
--    2026: "own deck only, nothing shared"). The shared deck of
--    20260919140000_flashcards.sql had no owner column. No student loses a
--    card they studied: each reviewed card goes to its first reviewer, every
--    other reviewer gets their own copy with their review history moved onto
--    it, and only cards nobody ever studied are removed. Generation stays
--    premium-only (gemini-chat), and is now built from the student's own weak
--    points.
-- 2. Per-question exam help ("ask the AI about this question" on a solved
--    paper) is stored on ai_learning_conversations, like every other AI turn:
--    one row is at once the daily-quota meter, the student's own cache and
--    their history, and the table's RLS (own SELECT, admin SELECT, no client
--    writes) is already exactly right for it.
-- 3. Deleting an account no longer leaves orphan AI and activity rows: four
--    per-student log tables had no foreign key at all.
--
-- The DELETEs only remove rows nobody can use any more: cards no student ever
-- studied, and rows of accounts that no longer exist.

-- ── 1. private flashcard decks ───────────────────────────────────────────
ALTER TABLE public.flashcards
  ADD COLUMN owner_id uuid
  CONSTRAINT flashcards_owner_id_fkey REFERENCES public.profiles(user_id) ON DELETE CASCADE;

-- A studied card goes to the student who reviewed it first...
UPDATE public.flashcards f
   SET owner_id = first_reviewer.student_id
  FROM (SELECT DISTINCT ON (flashcard_id) flashcard_id, student_id
          FROM public.student_flashcard_progress
         ORDER BY flashcard_id, created_at, id) first_reviewer
 WHERE first_reviewer.flashcard_id = f.id;

-- ...and every other student who reviewed it gets their own copy, with their
-- progress row moved onto it (ids made up front so the two statements agree).
CREATE TEMP TABLE card_copies ON COMMIT DROP AS
  SELECT gen_random_uuid() AS new_id, p.id AS progress_id, p.student_id, p.flashcard_id
    FROM public.student_flashcard_progress p
    JOIN public.flashcards f ON f.id = p.flashcard_id
   WHERE p.student_id <> f.owner_id;

INSERT INTO public.flashcards (id, owner_id, subject, chapter, front, back, concept, source, created_at, updated_at)
SELECT c.new_id, c.student_id, f.subject, f.chapter, f.front, f.back, f.concept, f.source, f.created_at, f.updated_at
  FROM card_copies c JOIN public.flashcards f ON f.id = c.flashcard_id;

UPDATE public.student_flashcard_progress p
   SET flashcard_id = c.new_id
  FROM card_copies c
 WHERE p.id = c.progress_id;

-- Cards nobody ever studied have nobody to belong to.
DELETE FROM public.flashcards WHERE owner_id IS NULL;

ALTER TABLE public.flashcards ALTER COLUMN owner_id SET NOT NULL;

-- Every read is "this student's deck", optionally narrowed to a chapter.
DROP INDEX IF EXISTS public.idx_flashcards_subject_chapter;
CREATE INDEX idx_flashcards_owner_subject_chapter
  ON public.flashcards USING btree (owner_id, subject, chapter);

-- The old USING (true) policy MUST go: permissive policies are OR'ed, so an
-- owner-only policy added next to it would change nothing.
DROP POLICY IF EXISTS "Authenticated users can view flashcards" ON public.flashcards;

CREATE POLICY "Students can view their own flashcards" ON public.flashcards
  FOR SELECT TO authenticated USING (owner_id = auth.uid());

-- Admins keep quality control over every deck. This SELECT policy is also
-- what lets the existing admin UPDATE/DELETE policies reach rows at all.
-- Student-facing reads therefore filter owner_id explicitly (useFlashcards),
-- or an admin's own study screen would show every student's cards.
CREATE POLICY "Admins can view all flashcards" ON public.flashcards
  FOR SELECT USING (public.is_admin());

-- A full chapter (10 cards) can only be regenerated by clearing it. Still no
-- student INSERT or UPDATE: cards are written by gemini-chat (service role),
-- and an UPDATE policy would let a student hand a card to someone else.
CREATE POLICY "Students can delete their own flashcards" ON public.flashcards
  FOR DELETE TO authenticated USING (owner_id = auth.uid());

-- Same body as 20260919140000, plus the ownership check the shared deck never
-- needed: a card id is no longer "a shared, non-sensitive resource". One error
-- for missing and foreign cards alike, so it can't confirm someone else's id.
CREATE OR REPLACE FUNCTION public.record_flashcard_review(p_flashcard_id uuid, p_recall_rating text)
RETURNS public.student_flashcard_progress
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_bump interval;
  v_row public.student_flashcard_progress;
BEGIN
  IF p_recall_rating NOT IN ('hard', 'medium', 'easy') THEN
    RAISE EXCEPTION 'Invalid recall rating: %', p_recall_rating;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.flashcards
                  WHERE id = p_flashcard_id AND owner_id = auth.uid()) THEN
    RAISE EXCEPTION 'Flashcard not found';
  END IF;

  v_bump := CASE p_recall_rating
    WHEN 'hard' THEN interval '1 day'
    WHEN 'medium' THEN interval '3 days'
    ELSE interval '7 days' -- 'easy'
  END;

  INSERT INTO public.student_flashcard_progress
    (student_id, flashcard_id, recall_rating, review_count, last_reviewed_at, next_review_at)
  VALUES
    (auth.uid(), p_flashcard_id, p_recall_rating, 1, now(), now() + v_bump)
  ON CONFLICT (student_id, flashcard_id) DO UPDATE SET
    recall_rating     = EXCLUDED.recall_rating,
    review_count      = public.student_flashcard_progress.review_count + 1,
    last_reviewed_at  = now(),
    next_review_at    = now() + v_bump
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;

REVOKE ALL ON FUNCTION public.record_flashcard_review(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.record_flashcard_review(uuid, text) TO authenticated, service_role;

-- ── 2. per-question exam help ────────────────────────────────────────────
-- exam_id: SET NULL, not CASCADE, like mistake_id — deleting a paper must not
-- hand the student back the daily-quota slots those rows count.
-- question_ref: "<index>|<question_number>" of the question in the cached
-- solution; the number pins it, because a regenerated solution can reorder.
ALTER TABLE public.ai_learning_conversations
  ADD COLUMN exam_id uuid
    CONSTRAINT ai_learning_conversations_exam_id_fkey REFERENCES public.exams(id) ON DELETE SET NULL,
  ADD COLUMN question_ref text;

CREATE INDEX idx_ai_conversations_exam
  ON public.ai_learning_conversations USING btree (exam_id) WHERE exam_id IS NOT NULL;

ALTER TABLE public.ai_learning_conversations
  DROP CONSTRAINT IF EXISTS ai_learning_conversations_mode_check;
ALTER TABLE public.ai_learning_conversations
  ADD CONSTRAINT ai_learning_conversations_mode_check
  CHECK (mode = ANY (ARRAY[
    'tutor'::text,
    'explain_mistake'::text,
    'solve_exam'::text,
    'generate_flashcards'::text,
    'exam_help'::text
  ]));
-- RLS unchanged on purpose. Never add a student DELETE policy here: these
-- rows ARE the daily quota counter.

-- ── 3. no orphans when an account is deleted ─────────────────────────────
-- Orphans first (rows of accounts already deleted), then the constraint.
DELETE FROM public.ai_learning_conversations c
 WHERE NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.user_id = c.user_id);
ALTER TABLE ONLY public.ai_learning_conversations
  ADD CONSTRAINT ai_learning_conversations_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(user_id) ON DELETE CASCADE;

DELETE FROM public.exam_activity_logs l
 WHERE NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.user_id = l.student_id);
ALTER TABLE ONLY public.exam_activity_logs
  ADD CONSTRAINT exam_activity_logs_student_id_fkey
  FOREIGN KEY (student_id) REFERENCES public.profiles(user_id) ON DELETE CASCADE;

DELETE FROM public.video_activity_logs l
 WHERE NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.user_id = l.student_id);
ALTER TABLE ONLY public.video_activity_logs
  ADD CONSTRAINT video_activity_logs_student_id_fkey
  FOREIGN KEY (student_id) REFERENCES public.profiles(user_id) ON DELETE CASCADE;

DELETE FROM public.student_questions_log l
 WHERE NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.user_id = l.student_id);
ALTER TABLE ONLY public.student_questions_log
  ADD CONSTRAINT student_questions_log_student_id_fkey
  FOREIGN KEY (student_id) REFERENCES public.profiles(user_id) ON DELETE CASCADE;
