// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkzgenjziliwkcdbcecc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1remdlbmp6aWxpd2tjZGJjZWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjc4NzUsImV4cCI6MjA3MTkwMzg3NX0.quNw8tlwm_0OCxPDe3DtDaojh31OIvni-8s5Wfs5iyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});